GET http://localhost/api/blogcontents

###
GET http://localhost/api/blogcontents/663aa0e5d3d0a9ac4e391e9b


###
POST  http://localhost/api/blogcontents
Content-Type: application/json

{
    "title": "Atualizar",
    "author": "Ivan",
    "content": "Add with NGINX - Delete",
    "publicationDate": "2024-05-05",
    "updatedAt": "2024-05-05",
    "category": "Teste",
    "keywords": ["Ivan"],
    "coverImage": "https://teste.jpeg",
    "tags": ["Ivan"],
    "language": "ptbr"
}

###
PATCH   http://localhost/api/blogcontents/663911c10ea6429635c46353
Content-Type: application/json

{
    "title": "Atualizar",
    "author": "Ivan",
    "content": "Atualizadocs",
    "publicationDate": "2024-05-05",
    "updatedAt": "2024-05-05",
    "category": "Teste",
    "keywords": ["Ivan"],
    "coverImage": "https://teste.jpeg",
    "tags": ["Ivan"],
    "language": "ptbr"
}

###
DELETE    http://localhost/api/blogcontents/663aa0e5d3d0a9ac4e391e9b