GET http://localhost:3000/blogcontents

###
GET http://localhost:3000/blogcontents/1

###
POST  http://localhost:3000/blogcontents
Content-Type: application/json

{
    "title": "foi!",
    "author": "Ivan",
    "content": "Applications often run in different environments. Depending on the environment, different configuration settings should be used. For example, usually the local environment relies on specific database credentials, valid only for the local DB instance. The production environment would use a separate set of DB credentials. Since configuration variables change, best practice is to store configuration variables in the environment.",
    "publicationDate": "2024-05-05",
    "updatedAt": "2024-05-05",
    "category": "Teste",
    "keywords": ["Ivan"],
    "coverImage": "https://teste.jpeg",
    "tags": ["Ivan"],
    "language": "ptbr"
}

###
PATCH   http://localhost:3000/blogcontents/1

###
DELETE    http://localhost:3000/blogcontents/1