GET http://localhost:3000/blogcontents

###
GET http://localhost:3000/blogcontents/663911c10ea6429635c46353

###
POST  http://localhost:3000/blogcontents
Content-Type: application/json

{
    "title": "Atualizar",
    "author": "Ivan",
    "content": "Atualize",
    "publicationDate": "2024-05-05",
    "updatedAt": "2024-05-05",
    "category": "Teste",
    "keywords": ["Ivan"],
    "coverImage": "https://teste.jpeg",
    "tags": ["Ivan"],
    "language": "ptbr"
}

###
PATCH   http://localhost:3000/blogcontents/663911c10ea6429635c46353
Content-Type: application/json

{
    "title": "Atualizar",
    "author": "Ivan",
    "content": "Atualizadocs",
    "publicationDate": "2024-05-05",
    "updatedAt": "2024-05-05",
    "category": "Teste",
    "keywords": ["Ivan"],
    "coverImage": "https://teste.jpeg",
    "tags": ["Ivan"],
    "language": "ptbr"
}

###
DELETE    http://localhost:3000/blogcontents/6638506c6d20396ec3b424ce